### ISSUE TITLE
Parsing error loading recipe citydecor

### ISSUE THREAD

**Issue by pavog** [TzarAnthony/ModernVanilla#1]
Hi, I'm running a fresh Forge 1.16.5 (36.2.34) server with [citydecor-1.16.5-1.0.0.jar](https://www.curseforge.com/minecraft/mc-mods/city-decor/files/3367187).

I get these errors on startup:

```
Parsing error loading recipe citydecor:green_cracked_concrete
com.google.gson.JsonSyntaxException: Unknown item 'citydecor:green_cracked_concrete'
```

```
Parsing error loading recipe citydecor:orange_cracked_concrete
com.google.gson.JsonSyntaxException: Unknown item 'citydecor:orange_cracked_concrete'
```

```
Parsing error loading recipe citydecor:pink_cracked_concrete
com.google.gson.JsonSyntaxException: Unknown item 'citydecor:pink_cracked_concrete'
```

And some more.
Full server log: https://mclo.gs/JEw79Lc

**Comment by TzarAnthony** [comment]
Thanks for raising this. I see the issue, I'll have it fixed in a few minutes.

**Comment by TzarAnthony** [comment]
Should be fixed now. Thank you!

Please reopen, if needed
